In [ ]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sn
%matplotlib inline
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.model_selection import KFold, train_test_split, cross_val_predict
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import AdaBoostClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler

# DATA

In [ ]:
#Upload File CSV
from google.colab import files
files.upload()

Saving alzheimer_oasis_dataset.csv to alzheimer_oasis_dataset.csv

{'alzheimer_oasis_dataset.csv': b'\xef\xbb\xbfSubject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF\r\nOAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2,27,0,1987,0.696,0.883\r\nOAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2,30,0,2004,0.681,0.876\r\nOAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,,23,0.5,1678,0.736,1.046\r\nOAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,,28,0.5,1738,0.713,1.010\r\nOAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,,22,0.5,1698,0.701,1.034\r\nOAS2_0004,OAS2_0004_MR1,Nondemented,1,0,F,R,88,18,3,28,0,1215,0.710,1.444\r\nOAS2_0004,OAS2_0004_MR2,Nondemented,2,538,F,R,90,18,3,27,0,1200,0.718,1.462\r\nOAS2_0005,OAS2_0005_MR1,Nondemented,1,0,M,R,80,12,4,28,0,1689,0.712,1.039\r\nOAS2_0005,OAS2_0005_MR2,Nondemented,2,1010,M,R,83,12,4,29,0.5,1701,0.711,1.032\r\nOAS2_0005,OAS2_0005_MR3,Nondemented,3,1603,M,R,85,12,4,30,0,1699,0.705,1.033\r\nOAS2_0007,OAS2_0007_MR1,Demented,1,0,M,R,71,16,,28,0.5,1357,0.748,1.293\r\nOAS2_0007,OAS2_0007_MR3,Demented,3,518,M,R,73,16,,27,1,1365,0.727,1.286\r\nOAS2_0007,OAS2_0007_MR4,Demented,4,1281,M,R,75,16,,27,1,1372,0.710,1.279\r\nOAS2_0008,OAS2_0008_MR1,Nondemented,1,0,F,R,93,14,2,30,0,1272,0.698,1.380\r\nOAS2_0008,OAS2_0008_MR2,Nondemented,2,742,F,R,95,14,2,29,0,1257,0.703,1.396\r\nOAS2_0009,OAS2_0009_MR1,Demented,1,0,M,R,68,12,2,27,0.5,1457,0.806,1.205\r\nOAS2_0009,OAS2_0009_MR2,Demented,2,576,M,R,69,12,2,24,0.5,1480,0.791,1.186\r\nOAS2_0010,OAS2_0010_MR1,Demented,1,0,F,R,66,12,3,30,0.5,1447,0.769,1.213\r\nOAS2_0010,OAS2_0010_MR2,Demented,2,854,F,R,68,12,3,29,0.5,1482,0.752,1.184\r\nOAS2_0012,OAS2_0012_MR1,Nondemented,1,0,F,R,78,16,2,29,0,1333,0.748,1.316\r\nOAS2_0012,OAS2_0012_MR2,Nondemented,2,730,F,R,80,16,2,29,0,1323,0.738,1.326\r\nOAS2_0012,OAS2_0012_MR3,Nondemented,3,1598,F,R,83,16,2,29,0,1323,0.718,1.327\r\nOAS2_0013,OAS2_0013_MR1,Nondemented,1,0,F,R,81,12,4,30,0,1230,0.715,1.427\r\nOAS2_0013,OAS2_0013_MR2,Nondemented,2,643,F,R,82,12,4,30,0,1212,0.720,1.448\r\nOAS2_0013,OAS2_0013_MR3,Nondemented,3,1456,F,R,85,12,4,29,0,1225,0.710,1.433\r\nOAS2_0014,OAS2_0014_MR1,Demented,1,0,M,R,76,16,3,21,0.5,1602,0.697,1.096\r\nOAS2_0014,OAS2_0014_MR2,Demented,2,504,M,R,77,16,3,16,1,1590,0.696,1.104\r\nOAS2_0016,OAS2_0016_MR1,Demented,1,0,M,R,88,8,4,25,0.5,1651,0.660,1.063\r\nOAS2_0016,OAS2_0016_MR2,Demented,2,707,M,R,90,8,4,23,0.5,1668,0.646,1.052\r\nOAS2_0017,OAS2_0017_MR1,Nondemented,1,0,M,R,80,12,3,29,0,1783,0.752,0.985\r\nOAS2_0017,OAS2_0017_MR3,Nondemented,3,617,M,R,81,12,3,27,0.5,1814,0.759,0.968\r\nOAS2_0017,OAS2_0017_MR4,Nondemented,4,1861,M,R,85,12,3,30,0,1820,0.755,0.964\r\nOAS2_0017,OAS2_0017_MR5,Nondemented,5,2400,M,R,86,12,3,27,0,1813,0.761,0.968\r\nOAS2_0018,OAS2_0018_MR1,Converted,1,0,F,R,87,14,1,30,0,1406,0.715,1.248\r\nOAS2_0018,OAS2_0018_MR3,Converted,3,489,F,R,88,14,1,29,0,1398,0.713,1.255\r\nOAS2_0018,OAS2_0018_MR4,Converted,4,1933,F,R,92,14,1,27,0.5,1423,0.696,1.234\r\nOAS2_0020,OAS2_0020_MR1,Converted,1,0,M,R,80,20,1,29,0,1587,0.693,1.106\r\nOAS2_0020,OAS2_0020_MR2,Converted,2,756,M,R,82,20,1,28,0.5,1606,0.677,1.093\r\nOAS2_0020,OAS2_0020_MR3,Converted,3,1563,M,R,84,20,1,26,0.5,1597,0.666,1.099\r\nOAS2_0021,OAS2_0021_MR1,Demented,1,0,M,R,72,20,1,26,0.5,1911,0.719,0.919\r\nOAS2_0021,OAS2_0021_MR2,Demented,2,1164,M,R,76,20,1,25,0.5,1926,0.736,0.911\r\nOAS2_0022,OAS2_0022_MR1,Nondemented,1,0,F,R,61,16,3,30,0,1313,0.805,1.337\r\nOAS2_0022,OAS2_0022_MR2,Nondemented,2,828,F,R,64,16,3,29,0,1316,0.796,1.333\r\nOAS2_0023,OAS2_0023_MR1,Demented,1,0,F,R,86,12,4,21,0.5,1247,0.662,1.407\r\nOAS2_0023,OAS2_0023_MR2,Demented,2,578,F,R,87,12,4,21,0.5,1250,0.652,1.405\r\nOAS2_0026,OAS2_0026_MR1,Demented,1,0,M,R,82,12,3,27,0.5,1420,0.713,1.236\r\nOAS2_0026,OAS2_0026_MR2,Demented,2,673,M,R,84,12,3,27,0.5,1445,0.695,1.214\r\nOAS2_0027,OAS2_0027_MR1,Nondemented,1,0,F,R,69,12,3,29,0,1365,0.783,1.286\r\nOAS2_0027,OAS2_0027_MR2,Nondemented,2,609,F,R,71,12,3,30,0,1360,0.782,1.291\r\nOAS2_0027,OAS2_0027_MR3,Nondemented,3,1234,F,R,73,12,3,30,0,1358,0.775,1.293\r\nOAS2_0027,OAS2_0027_MR4,Nondemented,4,1779,F,R,74,12,3,30,0,1353,0.772,1.297\r\nOAS2_0028,OAS2_0028_MR1,Demented,1,0,M,R,64,18,2,22,0.5,1547,0.737,1.134\r\nOAS2_0028,OAS2_0028_MR2,Demented,2,610,M,R,66,18,2,21,1,1562,0.717,1.124\r\nOAS2_0029,OAS2_0029_MR1,Nondemented,1,0,F,R,77,12,4,29,0,1377,0.734,1.275\r\nOAS2_0029,OAS2_0029_MR2,Nondemented,2,1099,F,R,80,12,4,30,0,1390,0.735,1.263\r\nOAS2_0030,OAS2_0030_MR1,Nondemented,1,0,F,R,60,18,1,30,0,1402,0.822,1.252\r\nOAS2_0030,OAS2_0030_MR2,Nondemented,2,932,F,R,62,18,1,30,0,1392,0.817,1.261\r\nOAS2_0031,OAS2_0031_MR1,Converted,1,0,F,R,86,12,3,30,0,1430,0.718,1.227\r\nOAS2_0031,OAS2_0031_MR2,Converted,2,446,F,R,88,12,3,30,0,1445,0.719,1.215\r\nOAS2_0031,OAS2_0031_MR3,Converted,3,1588,F,R,91,12,3,28,0.5,1463,0.696,1.199\r\nOAS2_0032,OAS2_0032_MR1,Demented,1,0,M,R,90,12,3,21,0.5,1307,0.679,1.342\r\nOAS2_0032,OAS2_0032_MR2,Demented,2,642,M,R,92,12,3,24,0.5,1311,0.676,1.339\r\nOAS2_0034,OAS2_0034_MR1,Nondemented,1,0,F,R,79,16,1,29,0,1466,0.703,1.197\r\nOAS2_0034,OAS2_0034_MR2,Nondemented,2,489,F,R,80,16,1,30,0,1450,0.698,1.210\r\nOAS2_0034,OAS2_0034_MR3,Nondemented,3,1287,F,R,82,16,1,30,0,1460,0.695,1.202\r\nOAS2_0034,OAS2_0034_MR4,Nondemented,4,1884,F,R,84,16,1,30,0,1453,0.684,1.208\r\nOAS2_0035,OAS2_0035_MR1,Nondemented,1,0,F,R,88,12,4,30,0,1336,0.738,1.313\r\nOAS2_0035,OAS2_0035_MR2,Nondemented,2,405,F,R,89,12,4,27,0,1329,0.733,1.320\r\nOAS2_0036,OAS2_0036_MR1,Nondemented,1,0,F,R,69,13,4,30,0,1359,0.789,1.291\r\nOAS2_0036,OAS2_0036_MR3,Nondemented,3,713,F,R,70,13,4,30,0,1361,0.783,1.290\r\nOAS2_0036,OAS2_0036_MR4,Nondemented,4,1770,F,R,73,13,4,30,0,1360,0.773,1.291\r\nOAS2_0036,OAS2_0036_MR5,Nondemented,5,2369,F,R,75,13,4,29,0,1349,0.778,1.301\r\nOAS2_0037,OAS2_0037_MR1,Demented,1,0,M,R,82,12,4,27,0.5,1477,0.729,1.188\r\nOAS2_0037,OAS2_0037_MR2,Demented,2,1123,M,R,85,12,4,29,0.5,1487,0.717,1.180\r\nOAS2_0037,OAS2_0037_MR3,Demented,3,2029,M,R,88,12,4,26,0.5,1483,0.709,1.184\r\nOAS2_0037,OAS2_0037_MR4,Demented,4,2508,M,R,89,12,4,26,0.5,1485,0.706,1.181\r\nOAS2_0039,OAS2_0039_MR1,Demented,1,0,F,R,81,18,2,26,0.5,1174,0.742,1.495\r\nOAS2_0039,OAS2_0039_MR2,Demented,2,486,F,R,83,18,2,25,0.5,1179,0.733,1.488\r\nOAS2_0040,OAS2_0040_MR1,Demented,1,0,M,R,84,6,4,25,0.5,1310,0.727,1.339\r\nOAS2_0040,OAS2_0040_MR2,Demented,2,567,M,R,86,6,4,27,0.5,1320,0.724,1.329\r\nOAS2_0040,OAS2_0040_MR3,Demented,3,1204,M,R,88,6,4,23,0.5,1348,0.713,1.302\r\nOAS2_0041,OAS2_0041_MR1,Converted,1,0,F,R,71,16,1,27,0,1289,0.771,1.362\r\nOAS2_0041,OAS2_0041_MR2,Converted,2,756,F,R,73,16,1,28,0,1295,0.768,1.356\r\nOAS2_0041,OAS2_0041_MR3,Converted,3,1331,F,R,75,16,1,28,0.5,1314,0.760,1.335\r\nOAS2_0042,OAS2_0042_MR1,Nondemented,1,0,F,R,70,17,3,29,0,1640,0.766,1.070\r\nOAS2_0042,OAS2_0042_MR2,Nondemented,2,1008,F,R,73,17,3,29,0,1665,0.748,1.054\r\nOAS2_0043,OAS2_0043_MR1,Demented,1,0,F,R,72,12,4,26,0.5,1453,0.777,1.208\r\nOAS2_0043,OAS2_0043_MR2,Demented,2,491,F,R,73,12,4,26,0.5,1451,0.757,1.210\r\nOAS2_0044,OAS2_0044_MR1,Demented,1,0,M,R,68,14,4,21,1,1333,0.685,1.317\r\nOAS2_0044,OAS2_0044_MR2,Demented,2,352,M,R,69,14,4,15,1,1331,0.678,1.318\r\nOAS2_0044,OAS2_0044_MR3,Demented,3,866,M,R,71,14,4,22,1,1332,0.679,1.317\r\nOAS2_0045,OAS2_0045_MR1,Nondemented,1,0,F,R,75,18,1,30,0,1317,0.737,1.332\r\nOAS2_0045,OAS2_0045_MR2,Nondemented,2,689,F,R,77,18,1,29,0,1322,0.731,1.327\r\nOAS2_0046,OAS2_0046_MR1,Demented,1,0,F,R,83,15,2,20,0.5,1476,0.750,1.189\r\nOAS2_0046,OAS2_0046_MR2,Demented,2,575,F,R,85,15,2,22,1,1483,0.748,1.183\r\nOAS2_0047,OAS2_0047_MR1,Nondemented,1,0,F,R,77,16,2,29,0,1433,0.723,1.225\r\nOAS2_0047,OAS2_0047_MR2,Nondemented,2,486,F,R,78,16,2,27,0,1414,0.727,1.242\r\nOAS2_0048,OAS2_0048_MR1,Demented,1,0,M,R,66,16,1,19,1,1695,0.711,1.036\r\nOAS2_0048,OAS2_0048_MR2,Demented,2,248,M,R,66,16,1,21,1,1708,0.703,1.028\r\nOAS2_0048,OAS2_0048_MR3,Demented,3,647,M,R,68,16,1,19,1,1712,0.691,1.025\r\nOAS2_0048,OAS2_0048_MR4,Demented,4,970,M,R,68,16,1,7,1,1714,0.682,1.024\r\nOAS2_0048,OAS2_0048_MR5,Demented,5,1233,M,R,69,16,1,4,1,1701,0.676,1.032\r\nOAS2_0049,OAS2_0049_MR1,Nondemented,1,0,F,R,69,16,3,30,0,1491,0.794,1.177\r\nOAS2_0049,OAS2_0049_MR2,Nondemented,2,395,F,R,70,16,3,30,0,1505,0.791,1.166\r\nOAS2_0049,OAS2_0049_MR3,Nondemented,3,687,F,R,71,16,3,30,0,1503,0.788,1.168\r\nOAS2_0050,OAS2_0050_MR1,Demented,1,0,M,R,71,12,4,20,0.5,1461,0.724,1.202\r\nOAS2_0050,OAS2_0050_MR2,Demented,2,538,M,R,72,12,4,17,1,1483,0.695,1.184\r\nOAS2_0051,OAS2_0051_MR1,Nondemented,1,0,F,R,92,23,1,29,0,1454,0.701,1.207\r\nOAS2_0051,OAS2_0051_MR2,Nondemented,2,457,F,R,94,23,1,29,0,1474,0.696,1.190\r\nOAS2_0051,OAS2_0051_MR3,Nondemented,3,1526,F,R,97,23,1,30,0,1483,0.689,1.184\r\nOAS2_0052,OAS2_0052_MR1,Nondemented,1,0,M,R,74,18,2,29,0,1463,0.737,1.199\r\nOAS2_0052,OAS2_0052_MR2,Nondemented,2,1510,M,R,78,18,2,30,0,1484,0.703,1.183\r\nOAS2_0053,OAS2_0053_MR1,Nondemented,1,0,F,R,82,16,3,29,0,1484,0.760,1.183\r\nOAS2_0053,OAS2_0053_MR2,Nondemented,2,842,F,R,84,16,3,28,0,1500,0.744,1.170\r\nOAS2_0054,OAS2_0054_MR1,Converted,1,0,F,R,85,18,1,29,0,1264,0.701,1.388\r\nOAS2_0054,OAS2_0054_MR2,Converted,2,846,F,R,87,18,1,24,0.5,1275,0.683,1.376\r\nOAS2_0055,OAS2_0055_MR1,Nondemented,1,0,M,R,65,13,3,29,0,1362,0.837,1.289\r\nOAS2_0055,OAS2_0055_MR2,Nondemented,2,726,M,R,67,13,3,27,0,1365,0.827,1.285\r\nOAS2_0056,OAS2_0056_MR1,Nondemented,1,0,F,R,71,14,2,28,0,1461,0.756,1.202\r\nOAS2_0056,OAS2_0056_MR2,Nondemented,2,622,F,R,73,14,2,30,0,1456,0.739,1.205\r\nOAS2_0057,OAS2_0057_MR1,Nondemented,1,0,F,R,81,12,2,30,0,1599,0.755,1.098\r\nOAS2_0057,OAS2_0057_MR2,Nondemented,2,640,F,R,83,12,2,29,0,1569,0.757,1.118\r\nOAS2_0057,OAS2_0057_MR3,Nondemented,3,1340,F,R,85,12,2,30,0,1580,0.739,1.111\r\nOAS2_0058,OAS2_0058_MR1,Demented,1,0,M,R,78,14,3,30,0.5,1315,0.707,1.335\r\nOAS2_0058,OAS2_0058_MR2,Demented,2,212,M,R,79,14,3,26,0.5,1308,0.706,1.341\r\nOAS2_0058,OAS2_0058_MR3,Demented,3,764,M,R,80,14,3,29,0.5,1324,0.695,1.326\r\nOAS2_0060,OAS2_0060_MR1,Demented,1,0,M,R,75,13,4,29,0.5,1416,0.766,1.239\r\nOAS2_0060,OAS2_0060_MR2,Demented,2,1290,M,R,78,13,4,28,0.5,1408,0.757,1.247\r\nOAS2_0061,OAS2_0061_MR1,Nondemented,1,0,M,R,68,18,1,30,0,1654,0.747,1.061\r\nOAS2_0061,OAS2_0061_MR2,Nondemented,2,873,M,R,70,18,1,30,0,1660,0.738,1.057\r\nOAS2_0061,OAS2_0061_MR3,Nondemented,3,1651,M,R,72,18,1,30,0,1681,0.729,1.044\r\nOAS2_0062,OAS2_0062_MR1,Nondemented,1,0,F,R,79,18,2,29,0,1641,0.695,1.069\r\nOAS2_0062,OAS2_0062_MR2,Nondemented,2,723,F,R,81,18,2,30,0,1664,0.677,1.055\r\nOAS2_0062,OAS2_0062_MR3,Nondemented,3,1351,F,R,83,18,2,29,0,1667,0.688,1.053\r\nOAS2_0063,OAS2_0063_MR1,Demented,1,0,F,R,80,12,,30,0.5,1430,0.737,1.228\r\nOAS2_0063,OAS2_0063_MR2,Demented,2,490,F,R,81,12,,27,0.5,1453,0.721,1.208\r\nOAS2_0064,OAS2_0064_MR1,Demented,1,0,F,R,78,8,5,23,1,1462,0.691,1.200\r\nOAS2_0064,OAS2_0064_MR2,Demented,2,830,F,R,81,8,5,26,0.5,1459,0.694,1.203\r\nOAS2_0064,OAS2_0064_MR3,Demented,3,1282,F,R,82,8,5,18,0.5,1464,0.682,1.199\r\nOAS2_0066,OAS2_0066_MR1,Demented,1,0,M,R,61,18,1,30,1,1957,0.734,0.897\r\nOAS2_0066,OAS2_0066_MR2,Demented,2,497,M,R,62,18,1,30,0.5,1928,0.731,0.910\r\nOAS2_0067,OAS2_0067_MR1,Nondemented,1,0,M,R,67,12,4,30,0,1440,0.727,1.219\r\nOAS2_0067,OAS2_0067_MR2,Nondemented,2,451,M,R,68,12,4,29,0,1438,0.738,1.220\r\nOAS2_0067,OAS2_0067_MR3,Nondemented,3,1438,M,R,71,12,4,29,0,1455,0.724,1.206\r\nOAS2_0067,OAS2_0067_MR4,Nondemented,4,2163,M,R,73,12,4,28,0,1444,0.722,1.215\r\nOAS2_0068,OAS2_0068_MR1,Nondemented,1,0,F,R,88,12,3,30,0,1428,0.700,1.229\r\nOAS2_0068,OAS2_0068_MR2,Nondemented,2,743,F,R,90,12,3,29,0,1475,0.676,1.190\r\nOAS2_0069,OAS2_0069_MR1,Nondemented,1,0,F,R,81,18,2,29,0,1470,0.687,1.194\r\nOAS2_0069,OAS2_0069_MR2,Nondemented,2,432,F,R,82,18,2,30,0,1471,0.690,1.193\r\nOAS2_0070,OAS2_0070_MR1,Nondemented,1,0,M,R,80,17,1,28,0,1660,0.728,1.057\r\nOAS2_0070,OAS2_0070_MR2,Nondemented,2,672,M,R,82,17,1,29,0,1692,0.723,1.037\r\nOAS2_0070,OAS2_0070_MR3,Nondemented,3,1415,M,R,84,17,1,29,0,1707,0.717,1.028\r\nOAS2_0070,OAS2_0070_MR4,Nondemented,4,1870,M,R,85,17,1,30,0,1724,0.704,1.018\r\nOAS2_0070,OAS2_0070_MR5,Nondemented,5,2386,M,R,86,17,1,30,0,1720,0.705,1.020\r\nOAS2_0071,OAS2_0071_MR1,Demented,1,0,F,R,83,13,2,27,1,1391,0.705,1.262\r\nOAS2_0071,OAS2_0071_MR2,Demented,2,365,F,R,84,13,2,28,1,1402,0.695,1.252\r\nOAS2_0073,OAS2_0073_MR1,Nondemented,1,0,F,R,70,14,3,29,0,1524,0.787,1.151\r\nOAS2_0073,OAS2_0073_MR2,Nondemented,2,580,F,R,72,14,3,28,0,1512,0.777,1.161\r\nOAS2_0073,OAS2_0073_MR3,Nondemented,3,1705,F,R,75,14,3,28,0,1507,0.782,1.164\r\nOAS2_0073,OAS2_0073_MR4,Nondemented,4,2288,F,R,76,14,3,29,0,1490,0.774,1.178\r\nOAS2_0073,OAS2_0073_MR5,Nondemented,5,2517,F,R,77,14,3,29,0,1504,0.769,1.167\r\nOAS2_0075,OAS2_0075_MR1,Demented,1,0,F,R,73,8,5,25,0.5,1151,0.743,1.525\r\nOAS2_0075,OAS2_0075_MR2,Demented,2,567,F,R,75,8,5,22,0.5,1143,0.741,1.535\r\nOAS2_0076,OAS2_0076_MR1,Nondemented,1,0,F,R,66,18,2,30,0,1504,0.725,1.167\r\nOAS2_0076,OAS2_0076_MR2,Nondemented,2,956,F,R,69,18,2,29,0,1536,0.719,1.143\r\nOAS2_0076,OAS2_0076_MR3,Nondemented,3,1663,F,R,71,18,2,30,0,1520,0.718,1.155\r\nOAS2_0077,OAS2_0077_MR1,Nondemented,1,0,M,R,69,16,2,28,0,1848,0.737,0.950\r\nOAS2_0077,OAS2_0077_MR2,Nondemented,2,1393,M,R,73,16,2,29,0,1931,0.722,0.909\r\nOAS2_0078,OAS2_0078_MR1,Nondemented,1,0,M,R,89,16,1,28,0,1631,0.674,1.076\r\nOAS2_0078,OAS2_0078_MR2,Nondemented,2,441,M,R,91,16,1,28,0,1640,0.670,1.070\r\nOAS2_0078,OAS2_0078_MR3,Nondemented,3,1019,M,R,92,16,1,30,0,1662,0.682,1.056\r\nOAS2_0079,OAS2_0079_MR1,Demented,1,0,F,R,69,12,4,23,0.5,1447,0.759,1.213\r\nOAS2_0079,OAS2_0079_MR2,Demented,2,584,F,R,71,12,4,16,1,1492,0.725,1.176\r\nOAS2_0079,OAS2_0079_MR3,Demented,3,1435,F,R,73,12,4,16,1,1478,0.696,1.188\r\nOAS2_0080,OAS2_0080_MR1,Demented,1,0,M,R,66,15,2,25,0.5,1548,0.727,1.134\r\nOAS2_0080,OAS2_0080_MR2,Demented,2,580,M,R,68,15,2,30,0.5,1556,0.713,1.128\r\nOAS2_0080,OAS2_0080_MR3,Demented,3,1209,M,R,69,15,2,28,0.5,1546,0.724,1.135\r\nOAS2_0081,OAS2_0081_MR1,Demented,1,0,F,R,82,12,4,26,0.5,1271,0.695,1.381\r\nOAS2_0081,OAS2_0081_MR2,Demented,2,659,F,R,84,12,4,26,0.5,1273,0.686,1.378\r\nOAS2_0085,OAS2_0085_MR1,Nondemented,1,0,F,R,78,8,5,29,0,1383,0.756,1.269\r\nOAS2_0085,OAS2_0085_MR2,Nondemented,2,670,F,R,80,8,5,27,0,1381,0.751,1.270\r\nOAS2_0086,OAS2_0086_MR1,Nondemented,1,0,F,R,63,15,2,28,0,1544,0.805,1.136\r\nOAS2_0086,OAS2_0086_MR2,Nondemented,2,802,F,R,65,15,2,28,0,1542,0.792,1.138\r\nOAS2_0087,OAS2_0087_MR1,Demented,1,0,F,R,96,17,1,26,1,1465,0.683,1.198\r\nOAS2_0087,OAS2_0087_MR2,Demented,2,754,F,R,98,17,1,21,2,1503,0.660,1.168\r\nOAS2_0088,OAS2_0088_MR1,Demented,1,0,M,R,78,12,4,21,1,1477,0.672,1.188\r\nOAS2_0088,OAS2_0088_MR2,Demented,2,751,M,R,80,12,4,20,1,1494,0.661,1.175\r\nOAS2_0089,OAS2_0089_MR1,Demented,1,0,M,R,70,12,2,29,0.5,1432,0.692,1.225\r\nOAS2_0089,OAS2_0089_MR3,Demented,3,563,M,R,72,12,2,27,1,1432,0.684,1.226\r\nOAS2_0090,OAS2_0090_MR1,Nondemented,1,0,M,R,73,18,2,29,0,1548,0.773,1.134\r\nOAS2_0090,OAS2_0090_MR2,Nondemented,2,680,M,R,75,18,2,29,0,1534,0.772,1.144\r\nOAS2_0090,OAS2_0090_MR3,Nondemented,3,1345,M,R,76,18,2,30,0,1550,0.758,1.133\r\nOAS2_0091,OAS2_0091_MR1,Nondemented,1,0,M,R,75,12,4,28,0,1511,0.739,1.162\r\nOAS2_0091,OAS2_0091_MR2,Nondemented,2,1047,M,R,78,12,4,29,0,1506,0.715,1.166\r\nOAS2_0092,OAS2_0092_MR1,Converted,1,0,F,R,83,12,2,28,0,1383,0.748,1.269\r\nOAS2_0092,OAS2_0092_MR2,Converted,2,706,F,R,84,12,2,27,0.5,1390,0.728,1.263\r\nOAS2_0094,OAS2_0094_MR1,Nondemented,1,0,F,R,61,16,1,30,0,1513,0.771,1.160\r\nOAS2_0094,OAS2_0094_MR2,Nondemented,2,817,F,R,63,16,1,30,0,1449,0.774,1.212\r\nOAS2_0095,OAS2_0095_MR1,Nondemented,1,0,M,R,71,18,1,30,0,1769,0.699,0.992\r\nOAS2_0095,OAS2_0095_MR2,Nondemented,2,673,M,R,72,18,1,29,0,1785,0.687,0.983\r\nOAS2_0095,OAS2_0095_MR3,Nondemented,3,1412,M,R,74,18,1,29,0,1814,0.679,0.967\r\nOAS2_0096,OAS2_0096_MR1,Nondemented,1,0,F,R,89,13,3,29,0,1154,0.750,1.521\r\nOAS2_0096,OAS2_0096_MR2,Nondemented,2,778,F,R,91,13,3,28,0,1165,0.736,1.506\r\nOAS2_0097,OAS2_0097_MR1,Nondemented,1,0,M,R,74,16,2,30,0,1611,0.729,1.089\r\nOAS2_0097,OAS2_0097_MR2,Nondemented,2,1024,M,R,77,16,2,30,0,1628,0.709,1.078\r\nOAS2_0098,OAS2_0098_MR1,Demented,1,0,M,R,66,12,4,30,0.5,1446,0.780,1.214\r\nOAS2_0098,OAS2_0098_MR2,Demented,2,661,M,R,67,12,4,28,0.5,1412,0.783,1.243\r\nOAS2_0099,OAS2_0099_MR1,Demented,1,0,F,R,80,12,,27,0.5,1475,0.762,1.190\r\nOAS2_0099,OAS2_0099_MR2,Demented,2,807,F,R,83,12,,23,0.5,1484,0.750,1.183\r\nOAS2_0100,OAS2_0100_MR1,Nondemented,1,0,F,R,77,11,4,29,0,1583,0.777,1.108\r\nOAS2_0100,OAS2_0100_MR2,Nondemented,2,1218,F,R,80,11,4,30,0,1586,0.757,1.107\r\nOAS2_0100,OAS2_0100_MR3,Nondemented,3,1752,F,R,82,11,4,30,0,1590,0.760,1.104\r\nOAS2_0101,OAS2_0101_MR1,Nondemented,1,0,F,R,71,18,2,30,0,1371,0.769,1.280\r\nOAS2_0101,OAS2_0101_MR2,Nondemented,2,952,F,R,74,18,2,30,0,1400,0.752,1.254\r\nOAS2_0101,OAS2_0101_MR3,Nondemented,3,1631,F,R,76,18,2,30,0,1379,0.757,1.273\r\nOAS2_0102,OAS2_0102_MR1,Demented,1,0,M,R,82,15,3,29,0.5,1499,0.689,1.171\r\nOAS2_0102,OAS2_0102_MR2,Demented,2,610,M,R,84,15,3,29,0.5,1497,0.686,1.172\r\nOAS2_0102,OAS2_0102_MR3,Demented,3,1387,M,R,86,15,3,30,0.5,1498,0.681,1.171\r\nOAS2_0103,OAS2_0103_MR1,Converted,1,0,F,R,69,16,1,30,0,1404,0.750,1.250\r\nOAS2_0103,OAS2_0103_MR2,Converted,2,1554,F,R,74,16,1,30,0.5,1423,0.722,1.233\r\nOAS2_0103,OAS2_0103_MR3,Converted,3,2002,F,R,75,16,1,30,0.5,1419,0.731,1.236\r\nOAS2_0104,OAS2_0104_MR1,Demented,1,0,M,R,70,16,1,25,0.5,1568,0.696,1.119\r\nOAS2_0104,OAS2_0104_MR2,Demented,2,465,M,R,71,16,1,17,1,1562,0.685,1.123\r\nOAS2_0105,OAS2_0105_MR1,Nondemented,1,0,M,R,86,12,4,29,0,1783,0.703,0.984\r\nOAS2_0105,OAS2_0105_MR2,Nondemented,2,675,M,R,87,12,4,30,0,1762,0.718,0.996\r\nOAS2_0106,OAS2_0106_MR1,Demented,1,0,F,R,70,11,4,22,1,1445,0.722,1.214\r\nOAS2_0106,OAS2_0106_MR2,Demented,2,729,F,R,72,11,4,21,1,1489,0.686,1.179\r\nOAS2_0108,OAS2_0108_MR1,Demented,1,0,M,R,77,18,1,25,0.5,1604,0.781,1.094\r\nOAS2_0108,OAS2_0108_MR2,Demented,2,883,M,R,79,18,1,27,0.5,1569,0.781,1.118\r\nOAS2_0109,OAS2_0109_MR1,Nondemented,1,0,M,R,81,11,4,28,0,1750,0.670,1.003\r\nOAS2_0109,OAS2_0109_MR2,Nondemented,2,766,M,R,83,11,4,29,0,1744,0.670,1.006\r\nOAS2_0111,OAS2_0111_MR1,Demented,1,0,M,R,62,12,4,17,0.5,1525,0.732,1.151\r\nOAS2_0111,OAS2_0111_MR2,Demented,2,881,M,R,65,12,4,17,0.5,1520,0.699,1.155\r\nOAS2_0112,OAS2_0112_MR1,Demented,1,0,F,R,76,12,3,27,0.5,1315,0.698,1.335\r\nOAS2_0112,OAS2_0112_MR2,Demented,2,558,F,R,78,12,3,20,0.5,1339,0.689,1.311\r\nOAS2_0113,OAS2_0113_MR1,Demented,1,0,F,R,73,13,2,23,0.5,1536,0.725,1.142\r\nOAS2_0113,OAS2_0113_MR2,Demented,2,504,F,R,75,13,2,28,0.5,1520,0.708,1.155\r\nOAS2_0114,OAS2_0114_MR1,Demented,1,0,F,R,76,12,,27,0.5,1316,0.727,1.333\r\nOAS2_0114,OAS2_0114_MR2,Demented,2,570,F,R,78,12,,27,1,1309,0.709,1.341\r\nOAS2_0116,OAS2_0116_MR1,Demented,1,0,F,R,73,12,3,27,0.5,1425,0.769,1.232\r\nOAS2_0116,OAS2_0116_MR2,Demented,2,616,F,R,75,12,3,28,0.5,1407,0.770,1.247\r\nOAS2_0117,OAS2_0117_MR1,Nondemented,1,0,M,R,73,20,2,30,0,1842,0.758,0.953\r\nOAS2_0117,OAS2_0117_MR2,Nondemented,2,576,M,R,74,20,2,30,0,1806,0.759,0.972\r\nOAS2_0117,OAS2_0117_MR3,Nondemented,3,1345,M,R,76,20,2,30,0,1823,0.739,0.963\r\nOAS2_0117,OAS2_0117_MR4,Nondemented,4,1927,M,R,78,20,2,29,0,1826,0.734,0.961\r\nOAS2_0118,OAS2_0118_MR1,Converted,1,0,F,R,67,14,4,30,0,1508,0.794,1.164\r\nOAS2_0118,OAS2_0118_MR2,Converted,2,1422,F,R,71,14,4,26,0.5,1529,0.788,1.147\r\nOAS2_0119,OAS2_0119_MR1,Nondemented,1,0,F,R,81,15,2,28,0,1486,0.754,1.181\r\nOAS2_0119,OAS2_0119_MR2,Nondemented,2,733,F,R,83,15,2,29,0,1482,0.751,1.184\r\nOAS2_0119,OAS2_0119_MR3,Nondemented,3,1713,F,R,85,15,2,30,0,1488,0.741,1.180\r\nOAS2_0120,OAS2_0120_MR1,Demented,1,0,F,R,76,14,3,25,1,1409,0.715,1.246\r\nOAS2_0120,OAS2_0120_MR2,Demented,2,595,F,R,78,14,3,15,2,1401,0.700,1.253\r\nOAS2_0121,OAS2_0121_MR1,Nondemented,1,0,F,R,73,11,4,30,0,1475,0.726,1.190\r\nOAS2_0121,OAS2_0121_MR2,Nondemented,2,647,F,R,74,11,4,30,0,1517,0.705,1.157\r\nOAS2_0122,OAS2_0122_MR1,Nondemented,1,0,F,R,86,16,3,30,0,1293,0.747,1.357\r\nOAS2_0122,OAS2_0122_MR2,Nondemented,2,597,F,R,88,16,3,30,0,1295,0.744,1.35

In [ ]:
data = pd.read_csv('alzheimer_oasis_dataset.csv')

In [ ]:
x = data.drop('Group', axis=1)
y = data['Group']

In [ ]:
data.head()

,Subject ID,MRI ID,Group,Visit,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,OAS2_0001,OAS2_0001_MR1,Nondemented,1,0,M,R,87,14,2.0,27.0,0.0,1987,0.696,0.883
1,OAS2_0001,OAS2_0001_MR2,Nondemented,2,457,M,R,88,14,2.0,30.0,0.0,2004,0.681,0.876
2,OAS2_0002,OAS2_0002_MR1,Demented,1,0,M,R,75,12,NaN,23.0,0.5,1678,0.736,1.046
3,OAS2_0002,OAS2_0002_MR2,Demented,2,560,M,R,76,12,NaN,28.0,0.5,1738,0.713,1.010
4,OAS2_0002,OAS2_0002_MR3,Demented,3,1895,M,R,80,12,NaN,22.0,0.5,1698,0.701,1.034

In [ ]:
data.shape

(373, 15)

In [ ]:
data.columns

Index(['Subject ID', 'MRI ID', 'Group', 'Visit', 'MR Delay', 'M/F', 'Hand',
       'Age', 'EDUC', 'SES', 'MMSE', 'CDR', 'eTIV', 'nWBV', 'ASF'],
      dtype='object')

In [ ]:
data.describe

<bound method NDFrame.describe of     Subject ID         MRI ID        Group  Visit  MR Delay M/F Hand  Age  \
0    OAS2_0001  OAS2_0001_MR1  Nondemented      1         0   M    R   87
1    OAS2_0001  OAS2_0001_MR2  Nondemented      2       457   M    R   88
2    OAS2_0002  OAS2_0002_MR1     Demented      1         0   M    R   75
3    OAS2_0002  OAS2_0002_MR2     Demented      2       560   M    R   76
4    OAS2_0002  OAS2_0002_MR3     Demented      3      1895   M    R   80
..         ...            ...          ...    ...       ...  ..  ...  ...
368  OAS2_0185  OAS2_0185_MR2     Demented      2       842   M    R   82
369  OAS2_0185  OAS2_0185_MR3     Demented      3      2297   M    R   86
370  OAS2_0186  OAS2_0186_MR1  Nondemented      1         0   F    R   61
371  OAS2_0186  OAS2_0186_MR2  Nondemented      2       763   F    R   63
372  OAS2_0186  OAS2_0186_MR3  Nondemented      3      1608   F    R   65

     EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0      14  2.0  27.0  0.0  1987  0.696  0.883
1      14  2.0  30.0  0.0  2004  0.681  0.876
2      12  NaN  23.0  0.5  1678  0.736  1.046
3      12  NaN  28.0  0.5  1738  0.713  1.010
4      12  NaN  22.0  0.5  1698  0.701  1.034
..    ...  ...   ...  ...   ...    ...    ...
368    16  1.0  28.0  0.5  1693  0.694  1.037
369    16  1.0  26.0  0.5  1688  0.675  1.040
370    13  2.0  30.0  0.0  1319  0.801  1.331
371    13  2.0  30.0  0.0  1327  0.796  1.323
372    13  2.0  30.0  0.0  1333  0.801  1.317

[373 rows x 15 columns]>

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Subject ID  373 non-null    object
 1   MRI ID      373 non-null    object
 2   Group       373 non-null    object
 3   Visit       373 non-null    int64
 4   MR Delay    373 non-null    int64
 5   M/F         373 non-null    object
 6   Hand        373 non-null    object
 7   Age         373 non-null    int64
 8   EDUC        373 non-null    int64
 9   SES         354 non-null    float64
 10  MMSE        371 non-null    float64
 11  CDR         373 non-null    float64
 12  eTIV        373 non-null    int64
 13  nWBV        373 non-null    float64
 14  ASF         373 non-null    float64
dtypes: float64(5), int64(5), object(5)
memory usage: 43.8+ KB

In [ ]:
from sklearn.preprocessing import LabelEncoder

# DATA PREPROCESSING

In [ ]:
lab=LabelEncoder()

In [ ]:
data = data.drop(data[['Subject ID','MRI ID', 'Visit']], axis=1)
data.head()

,Group,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
0,Nondemented,0,M,R,87,14,2.0,27.0,0.0,1987,0.696,0.883
1,Nondemented,457,M,R,88,14,2.0,30.0,0.0,2004,0.681,0.876
2,Demented,0,M,R,75,12,NaN,23.0,0.5,1678,0.736,1.046
3,Demented,560,M,R,76,12,NaN,28.0,0.5,1738,0.713,1.010
4,Demented,1895,M,R,80,12,NaN,22.0,0.5,1698,0.701,1.034

In [ ]:
data.Group.value_counts()

Nondemented    190
Demented       146
Converted       37
Name: Group, dtype: int64

In [ ]:
#menggabungkan data kelas converted ke demented
data['Group']=data['Group'].replace(['Converted'],['Demented'])

In [ ]:
data.Group.value_counts()

Nondemented    190
Demented       183
Name: Group, dtype: int64

In [ ]:
data['M/F'] = lab.fit_transform(data['M/F'])
data['Group'] = lab.fit_transform (data['Group'])
data['Hand'] = lab.fit_transform(data['Hand'])
data.head()

   Group  MR Delay  M/F  Hand  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0      1         0    1     0   87    14  2.0  27.0  0.0  1987  0.696  0.883
1      1       457    1     0   88    14  2.0  30.0  0.0  2004  0.681  0.876
2      0         0    1     0   75    12  NaN  23.0  0.5  1678  0.736  1.046
3      0       560    1     0   76    12  NaN  28.0  0.5  1738  0.713  1.010
4      0      1895    1     0   80    12  NaN  22.0  0.5  1698  0.701  1.034

In [ ]:
data.tail()

     Group  MR Delay  M/F  Hand  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
368      0       842    1     0   82    16  1.0  28.0  0.5  1693  0.694  1.037
369      0      2297    1     0   86    16  1.0  26.0  0.5  1688  0.675  1.040
370      1         0    0     0   61    13  2.0  30.0  0.0  1319  0.801  1.331
371      1       763    0     0   63    13  2.0  30.0  0.0  1327  0.796  1.323
372      1      1608    0     0   65    13  2.0  30.0  0.0  1333  0.801  1.317

In [ ]:
data.shape

(373, 12)

In [ ]:
data.isnull().sum()

Group        0
MR Delay     0
M/F          0
Hand         0
Age          0
EDUC         0
SES         19
MMSE         2
CDR          0
eTIV         0
nWBV         0
ASF          0
dtype: int64

In [ ]:
#pengisian data kosong menggunakan nilai modus & mean
modus = data['SES'].mode()[0]
data['SES']=data['SES'].fillna(modus)
data['MMSE']=data['MMSE'].fillna(data['MMSE'].mean())

In [ ]:
data.isna().sum()

Group       0
MR Delay    0
M/F         0
Hand        0
Age         0
EDUC        0
SES         0
MMSE        0
CDR         0
eTIV        0
nWBV        0
ASF         0
dtype: int64

In [ ]:
#duplicate data check
data.duplicated().sum()

0

In [ ]:
data.Group.value_counts()

1    190
0    183
Name: Group, dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 373 entries, 0 to 372
Data columns (total 12 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Group     373 non-null    int64
 1   MR Delay  373 non-null    int64
 2   M/F       373 non-null    int64
 3   Hand      373 non-null    int64
 4   Age       373 non-null    int64
 5   EDUC      373 non-null    int64
 6   SES       373 non-null    float64
 7   MMSE      373 non-null    float64
 8   CDR       373 non-null    float64
 9   eTIV      373 non-null    int64
 10  nWBV      373 non-null    float64
 11  ASF       373 non-null    float64
dtypes: float64(5), int64(7)
memory usage: 35.1 KB

In [ ]:
#normalisasi data menggunakan min-max norm
data['MMSE']=(data['MMSE']-data['MMSE'].min())/(data['MMSE'].max()-data['MMSE'].min())
data['eTIV']=(data['eTIV']-data['eTIV'].min())/(data['eTIV'].max()-data['eTIV'].min())

In [ ]:
data.shape

(373, 12)

In [ ]:
data.describe(include='all')

,Group,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
count,373.000000,373.000000,373.000000,373.0,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000,373.000000
mean,0.509383,595.104558,0.428954,0.0,77.013405,14.597855,2.436997,0.897781,0.290885,0.425533,0.729568,1.195461
std,0.500583,635.485118,0.495592,0.0,7.640957,2.876339,1.109307,0.141282,0.374557,0.196146,0.037135,0.138092
min,0.000000,0.000000,0.000000,0.0,60.000000,6.000000,1.000000,0.000000,0.000000,0.000000,0.644000,0.876000
25%,0.000000,0.000000,0.000000,0.0,71.000000,12.000000,2.000000,0.884615,0.000000,0.279510,0.700000,1.099000
50%,1.000000,552.000000,0.000000,0.0,77.000000,15.000000,2.000000,0.961538,0.000000,0.405345,0.729000,1.194000
75%,1.000000,873.000000,1.000000,0.0,82.000000,16.000000,3.000000,1.000000,0.500000,0.546771,0.756000,1.293000
max,1.000000,2639.000000,1.000000,0.0,98.000000,23.000000,5.000000,1.000000,2.000000,1.000000,0.837000,1.587000

In [ ]:
x=data.iloc[:,data.columns!='Group']
y=data.iloc[:,data.columns=='Group']

In [ ]:
x.shape

(373, 11)

In [ ]:
y.shape

(373, 1)

In [ ]:
x.head()

   MR Delay  M/F  Hand  Age  EDUC  SES      MMSE  CDR      eTIV   nWBV    ASF
0         0    1     0   87    14  2.0  0.884615  0.0  0.981069  0.696  0.883
1       457    1     0   88    14  2.0  1.000000  0.0  1.000000  0.681  0.876
2         0    1     0   75    12  2.0  0.730769  0.5  0.636971  0.736  1.046
3       560    1     0   76    12  2.0  0.923077  0.5  0.703786  0.713  1.010
4      1895    1     0   80    12  2.0  0.692308  0.5  0.659243  0.701  1.034

In [ ]:
y.head()

   Group
0      1
1      1
2      0
3      0
4      0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score, roc_curve, auc

In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2)

In [ ]:
xtrain.head()

,MR Delay,M/F,Hand,Age,EDUC,SES,MMSE,CDR,eTIV,nWBV,ASF
177,0,0,0,82,12,4.0,0.846154,0.5,0.183742,0.695,1.381
101,1233,1,0,69,16,1.0,0.000000,1.0,0.662584,0.676,1.032
17,0,0,0,66,12,3.0,1.000000,0.5,0.379733,0.769,1.213
220,2002,0,0,75,16,1.0,1.000000,0.5,0.348552,0.731,1.236
344,700,1,0,72,16,4.0,0.923077,0.5,0.768374,0.732,0.977

In [ ]:
ytrain.head()

     Group
177      0
101      0
17       0
220      0
344      0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.tree import DecisionTreeClassifier

# PERCENTAGE SPLIT

**C4.5 PERCENTAGE SPLIT VALIDATION**

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=1)
tree_data = DecisionTreeClassifier(random_state=1)
tree_data.fit(x_train,y_train)

DecisionTreeClassifier(random_state=1)

In [ ]:
y_pred = tree_data.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
print ("Confusion Matrix")
print (cm)
akurasi = classification_report(y_test,y_pred)
print ("Tingkat Akurasi Algoritma C4.5 dengan percentage split")
print ("Akurasi : ", akurasi)
akurasi = accuracy_score(y_test,y_pred)
print ("Tingkat akurasi : %d persen" %(akurasi*100))

Confusion Matrix
[[28  4]
 [ 5 38]]
Tingkat Akurasi Algoritma C4.5 dengan percentage split
Akurasi :                precision    recall  f1-score   support

           0       0.85      0.88      0.86        32
           1       0.90      0.88      0.89        43

    accuracy                           0.88        75
   macro avg       0.88      0.88      0.88        75
weighted avg       0.88      0.88      0.88        75

Tingkat akurasi : 88 persen

In [ ]:
from sklearn.tree import export_graphviz
export_graphviz(tree_data, out_file="Tree_Category.dot", class_names=["0","1","2"],
                feature_names=x.columns, impurity=False, filled=True)

In [ ]:
import graphviz

with open("Tree_Category.dot") as fig:
  dot_graph = fig.read()
  graph = graphviz.Source(dot_graph)

graph.view()

'Source.gv.pdf'

**ADABOOST PERCENTAGE SPLIT**

In [ ]:
# Buat model Adaboost dengan Decision Tree Classifier sebagai estimator
x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.2, random_state=1)
adaboost = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2), n_estimators=373)
# Menghitung akurasi dan confusion matrix pada testing set
adaboost.fit(x_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
                   n_estimators=373)

In [ ]:
y_pred_test = adaboost.predict(x_test)
acc = accuracy_score(y_test, y_pred_test)
cm_test = confusion_matrix(y_test, y_pred_test)

In [ ]:
print ("Confusion Matrix")
print (cm_test)
akurasi = classification_report(y_test,y_pred_test)
print ("Tingkat Akurasi Algoritma AdaBoost dengan Percentage Split")
print (akurasi)
print ("Tingkat akurasi : %d persen" %(acc*100))

Confusion Matrix
[[27  5]
 [ 3 40]]
Tingkat Akurasi Algoritma AdaBoost dengan Percentage Split
              precision    recall  f1-score   support

           0       0.90      0.84      0.87        32
           1       0.89      0.93      0.91        43

    accuracy                           0.89        75
   macro avg       0.89      0.89      0.89        75
weighted avg       0.89      0.89      0.89        75

Tingkat akurasi : 89 persen

# K-FOLD CROSS VALIDATION

**C4.5 K-FOLD CROSS VALIDATION**

In [ ]:
#melakukan cross validation
x_train, x_test, y_train, y_test = train_test_split(x, y)
classifier = DecisionTreeClassifier(random_state=10)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(random_state=10)

In [ ]:
#menghitung akurasi cross validation
scores= cross_val_score(classifier, x_train, y_train, scoring ='accuracy', cv=10)
scores

array([1.        , 0.92857143, 0.96428571, 0.85714286, 0.89285714,
       0.92857143, 0.71428571, 1.        , 0.92857143, 0.92592593])

In [ ]:
pred = cross_val_predict(classifier, x, y, cv=10)
pred

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1])

In [ ]:
#Menghitung akurasi
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, pred)
print(confusion_matrix)

[[168  15]
 [ 25 165]]

In [ ]:
print(classification_report(y, pred))

              precision    recall  f1-score   support

           0       0.87      0.92      0.89       183
           1       0.92      0.87      0.89       190

    accuracy                           0.89       373
   macro avg       0.89      0.89      0.89       373
weighted avg       0.89      0.89      0.89       373

In [ ]:
#K-Fold Cross Validation
print(f'Tingkat akurasi: {(accuracy_score(y, pred)) * 100}%')

Tingkat akurasi: 89.27613941018767%

In [ ]:
from sklearn.tree import export_graphviz
export_graphviz(tree_data, out_file="Tree_Category.dot", class_names=["0","1","2"],
                feature_names=x.columns, impurity=False, filled=True)

In [ ]:
import graphviz

with open("Tree_Category.dot") as fig:
  dot_graph = fig.read()
  graph = graphviz.Source(dot_graph)

graph.view()

'Source.gv.pdf'

**ADABOOST KFOLD CROSS VALIDATION**

In [ ]:
#melakukan cross validation
x_train, x_test, y_train, y_test = train_test_split(x, y)
adaboostfold = AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2), n_estimators=373)
adaboostfold.fit(x_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
                   n_estimators=373)

In [ ]:
#menghitung akurasi cross validation
score= cross_val_score(adaboostfold, x, y, scoring ='accuracy', cv=10)
score

array([0.92105263, 0.86842105, 0.86842105, 0.91891892, 0.91891892,
       0.94594595, 0.89189189, 0.89189189, 0.97297297, 0.91891892])

In [ ]:
y_predict = cross_val_predict(adaboostfold, x, y, cv=10)
y_predict

array([1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1])

In [ ]:
#Menghitung akurasi
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y, y_predict)
print(confusion_matrix)

[[165  18]
 [ 15 175]]

In [ ]:
print(classification_report(y, y_predict))
accc = accuracy_score(y, y_predict)
print(f'Tingkat akurasi: {accc:.2f}%')

              precision    recall  f1-score   support

           0       0.92      0.90      0.91       183
           1       0.91      0.92      0.91       190

    accuracy                           0.91       373
   macro avg       0.91      0.91      0.91       373
weighted avg       0.91      0.91      0.91       373

Tingkat akurasi: 0.91%

In [ ]:
print(f'Tingkat akurasi: {(accuracy_score(y, y_predict)) * 100}%')

Tingkat akurasi: 91.15281501340483%